/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class Win32RegKeyTest_Win32RegKeyNameEnumeration */

#ifndef _Included_Win32RegKeyTest_Win32RegKeyNameEnumeration
#define _Included_Win32RegKeyTest_Win32RegKeyNameEnumeration
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     Win32RegKeyTest_Win32RegKeyNameEnumeration
 * Method:    nextElement
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_Win32RegKeyTest_Win32RegKeyNameEnumeration_nextElement
  (JNIEnv *, jobject);

/*
 * Class:     Win32RegKeyTest_Win32RegKeyNameEnumeration
 * Method:    hasMoreElements
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_Win32RegKeyTest_Win32RegKeyNameEnumeration_hasMoreElements
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
